spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: eea77b899ad8001da9a2
            client-secret: 78e382760f5f9bc3e78c5b523b8d4e503760d7b7
logging:
  level:
    org.springframework.security: DEBUG